terrestris/docker-geoserver

- README.md
- startup.sh
By adding something like
```
--mount src="/dir/with/libs/on/host",target=/opt/additional_libs,type=bind
```
to your `docker run` command you can easily add libs to a "fix" docker image. Note: The `target` value should not be changed.
Please review @hwbllmnn
> Add libs before starting the tomcat

- Dockerfile
This fixes the currently failing build, which is related to changes in the edge repo regarding gdal/libcrypto.
@dnlkoch @marcjansen
> Fix the build

- Dockerfile
- util/gs-release-check.sh
This is an enhancement of the docker release script as this will release all versions >= v2.5 - even if a version lower than the latest has been released on maintenance in the meantime (e.g. v2.13.3. has been released after v2.14.0)
Also contains some smaller adjustments:
* an explicit tag for the parent tomcat docker image is now used (instead of latest)
* we will only process GS versions later than 2.4.8, i.e. starting with v2.5
@marcjansen @dnlkoch
> Release all versions

- Dockerfile
This allows to pass extra java opts as an environment variable.
For example `docker run -it -p 80:8080 -e EXTRA_JAVA_OPTS='-Xms2g -Xmx4g' {YOUR_IMAGE_NAME}` or when using docker-compose
Please review @terrestris/devs
> Enable EXTRA_JAVA_OPTS as env variable

- Dockerfile
This adds the `nss` package to fix the following error during the start of the container:
```
java.security.ProviderException: Could not initialize NSS
```
Please review @buehner.
> Install nss package

- Dockerfile
In the past there have been issues when using the importer extension and importing raster data that
gdal was not able to find the proj library.
This issue could be tracked down to the usage of gdal from an unstable source.
This fix uses another base-image, which leads to a slight increase of the image size of about 20% but fixes the issue.
> Fixing issues with gdal and proj by switching base image

- .github/workflows/build-and-push-docker.yml
As docker hub does not provide free docker image builds anymore, we now use the github action worfklows for this.
> Migrate docker build to github actions

- Dockerfile
- README.md
Migrate from OpenJDK8 to OpenJDK11 by switching the base image. This change also contains all necessary (path) adjustments related to the jdk change.
> Migrate from OpenJDK8 to OpenJDK11

- Dockerfile
As suggested in https://github.com/terrestris/docker-geoserver/issues/20, this will build the geostyler plugin into the resulting docker image.
> Add geostyler plugin to docker image

- Dockerfile
This seems to work and would reduce the resulting docker image, but it may have unknown side effects in future in case JDK features are expected!?
> Use slim JRE base image

- Dockerfile
- README.md
- additional_fonts/.gitignore
- startup.sh
This adds the new feature to add custom fonts (*.ttf files)
By default, the base image only provides 26 fonts. This may not be sufficient if you need custom fonts for SLD styling.
This PR enables the possibility to add custom fonts via a mounted directory.
> feature: Add custom fonts (e.g. for SLD styling)

- README.md
- docker-compose-demo.yml
This adds a simple docker-compose demo to demonstrate the possibilities of the docker image.
The demo is using the `context` feature and the local `Dockerfile`, but in case you are using a pre-built image from dockerhub, all features of the `environment` and `volumes` are available (e.g. using custom java opts or adding custom libs and fonts)
This will pretty sure be extended with upcoming features i am planning to implement
> Add docker-compose demo

- Dockerfile
- README.md
- docker-compose-demo.yml
- startup.sh
This PR enables (optional) CORS support.
In most scenarios you will probably configure CORS on a proxy level, but in case you want to enable CORS in the geoserver directly, this can be done easily now by setting the new environment variable `CORS_ENABLED` to `true`. In that case, the `startup.sh` script will add the necessary filter definitions to the `web.xml`.
Origins, methods and headers can (optionally) be configured with these new environment values:
* `CORS_ALLOWED_ORIGINS` (default: `*`)
* `CORS_ALLOWED_METHODS` (default: `GET,POST,PUT,DELETE,HEAD,OPTIONS`)
* `CORS_ALLOWED_HEADERS` (default: `*`)
By default, CORS is **not** enabled!
> Add CORS support

- Dockerfile
Just a minor change: Refactoring the definition of CATALINA_OPTS to make it more readable.
Also added these new values:
* -Djava.awt.headless=true -server
* -Djavax.servlet.request.encoding=UTF-8
* -Djavax.servlet.response.encoding=UTF-8
> Refactor CATALINA_OPTS definition

- Dockerfile
- docker-compose-demo.yml
- install-extensions.sh
- startup.sh
This introduces a new feature:
By setting the new `INSTALL_EXTENSIONS` environment variable to `true` and configuring a comma separated list of extensions in the new env `STABLE_EXTENSIONS`, the startup script will download and install these extensions before starting the tomcat.
Probably you do not want to use this feature in production, but for quick or dev setups, this can be very helpful as you do not have to care about all of your extensions in the correct version, but can simply configure them.
See docker compose demo
> feature: Download configured extensions on startup

- startup.sh
This is an important bug fix.
In case the same container has been started multiple times, the cors definition would have been added also multiple times. This leads to multiple defintion of the same filter and GeoServer will not start up anymore.
This change fixes this by checking whether the filter already exists.
> fix: avoid multiple adding of cors filter

- util/gs-release-check.sh
A bug occured in the cronjobbed release script as we have more than 100 branches now, so we have to fetch all branches via Github API
> Fetch more than 100 branches

- Dockerfile
- docker-compose-demo.yml
With these changes simply adding the GeoServer grass raster datastore jar and the `gdal.jar` is sufficient to get GRASS support.
Switches to ubuntu 22.04 as base image as the debian gdal-grass driver does currently not work even when compiled from source.
Please review @terrestris/devs
> Prepare for grass raster datastore

- Dockerfile
Title says it all.
Required due to https://spring.io/blog/2022/04/01/spring-framework-rce-mitigation-alternative
Plz review @terrestris/devs
> Update tomcat to version 9.0.62

- Dockerfile
In case you want to build older versions (< 2.16.0), geostyler extension is not available, so we need this check to ensure that build is still working
> Check for geostyler compatibility

- Dockerfile
Title says it all.
Since `curl` is used in [install-extensions.sh](https://github.com/terrestris/docker-geoserver/blob/master/install-extensions.sh) it has to be installed.
Plz review @terrestris/devs
> Install curl required in script for extension install

- Dockerfile
Whenever a GeoStyler community plugin JAR is not available at https://repo.osgeo.org/#browse/browse:Geoserver-releases:org%2Fgeoserver%2Fcommunity%2Fgs-geostyler the Dockerfile will build the JAR itself based on the sources. Due to some refactoring, git and maven were not available, so these dependencies should be installed
This occured only for the 2.20.4 until now and could be fixed like this: https://github.com/terrestris/docker-geoserver/commit/eca97b2cd53d2515ec86fc420bbfbcff45281f06
So this should also be merge in master to enhance future stability
> Install maven and git

- Dockerfile
Removes the uninstall of `zip`, `unzip`, `wget` and `curl` because these are required to run [install-extensions.sh](https://github.com/terrestris/docker-geoserver/blob/master/install-extensions.sh) during runtime.
@terrestris/devs Please review
> fix: do not uninstall requried packages
